name: lazy_extensions
description: Provide extensions and functions for various types to save time and efforts.
version: 2.0.0
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  http: ^1.0.0
  intl: ^0.18.0
  universal_html: ^2.2.3
  url_launcher: ^6.1.11

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
