name: lazy_sign_in
description: Base package for [lazy_sign_in_extension] and [lazy_sign_in_google].

version: 2.1.0
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lazy_log: ^2.0.0
  # lazy_log:
  #   path: ../lazy_log

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
