name: lazy_sign_in_extension
description: Chrome/Firefox extension Google sign-in library base on [LazySignIn]
version: 2.1.1
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  js: ^0.6.7
  lazy_extensions: ^2.1.0
  lazy_log: ^2.0.0
  lazy_sign_in: ^2.1.0
  # lazy_log:
  #   path: ../lazy_log
  # lazy_sign_in:
  #   path: ../lazy_sign_in

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
