name: lazy_cache
description: Provides an indexed local storage on top of the shared_preferences package.
version: 2.0.0
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  json_preferences: ^2.0.0
  lazy_log: ^2.0.0
  # json_preferences:
  #   path: ../json_preferences
  # lazy_log:
  #   path: ../lazy_log

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
