name: lazy_http_client
description: Simple http client class that will auto apply specified headers on all requests.

version: 2.0.0
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  http: ^1.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
